name: Compile & Release

on:
  # Trigger the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release:
        description: Release-Version (leave empty to skip Release)
        default: ""
      release_name:
        description: Release-Name
        default: ""

jobs:
  compile_and_release:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v4

    - name: Create .love distribution file
      run: |
        7z a -tzip game.love ./*  -x!releases/

    - name: Save .love distribution file as artifact
      uses: actions/upload-artifact@v4
      with:
        path: "game.love"
        name: "game.love" # Default is 'artifact'
        retention-days: 30

    - name: Release
      if: ${{ github.event.inputs.release != '' }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.event.inputs.release }}
        name: "Version ${{ github.event.inputs.release }}: ${{ github.event.inputs.release_name }}"
        files: "*.love"
