name: Compile & Release

on:
  # Trigger the workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      release:
        description: Release-Version (leave empty to skip Release)
        default: ""
      release_name:
        description: Release-Name
        default: ""

jobs:
  compile_and_release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      LOVE_FILE: "blobbyvolley-${{ github.event.inputs.release || 'latest' }}.love"
      WIN64_FILE: "blobbyvolley-${{ github.event.inputs.release || 'latest' }}-win64.zip"

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE
    - uses: actions/checkout@v4

    - name: Create .love distribution file
      run: |
        mkdir -p .release/
        7z a -tzip .release/$LOVE_FILE ./*

    - name: Save .love distribution file as artifact
      uses: actions/upload-artifact@v4
      with:
        path: .release/${{ env.LOVE_FILE }}
        name: ${{ env.LOVE_FILE }} # Default is 'artifact'
        retention-days: 30

    - name: Release
      if: ${{ github.event.inputs.release != '' }}
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.event.inputs.release }}
        name: "Version ${{ github.event.inputs.release }}: ${{ github.event.inputs.release_name }}"
        generate_release_notes: true
        files: .release/*
